version: '2.1'

services:
  code-firefighter:
    image: code-firefighter
    build: .
    environment:
      NODE_ENV: production
      MONGO_DB: code-firefighter
      PORT: 3000
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"