version: '2.1'

services:
  code-firefighter:
    image: code-firefighter
    build: .
    environment:
      NODE_ENV: production
      MONGO_DB: firefighter
      MONGO_URL: mongodb://mongo:27017
      REDIS_URL: redis://redis:6379
      PORT: 3000
    ports:
      - "3000:3000"
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    volumes:
      - db-mongo:/data/db
    ports:
      - "27017:27017"
  redis:
    image: redis
    ports:
      - "6379:6379"
volumes:
  db-mongo:
    driver: local